popDomains = [{title:"百度知道 ",url:"zhidao.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"百度地图",url:"map.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"人民网",url:"www.people.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"淘宝网",url:"www.taobao.com",providerName:"popDomainProvider",relevancy:0},
{title:"58同城 ",url:"www.58.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜搜",url:"www.soso.com",providerName:"popDomainProvider",relevancy:0},
{title:"豆瓣",url:"www.douban.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪博客",url:"blog.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"土豆网",url:"www.tudou.com",providerName:"popDomainProvider",relevancy:0},
{title:"酷6网",url:"www.ku6.com",providerName:"popDomainProvider",relevancy:0},
{title:"百度知道 ",url:"zhidao.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"百度地图",url:"map.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"人民网",url:"www.people.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"淘宝网",url:"www.taobao.com",providerName:"popDomainProvider",relevancy:0},
{title:"58同城 ",url:"www.58.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜搜",url:"www.soso.com",providerName:"popDomainProvider",relevancy:0},
{title:"豆瓣",url:"www.douban.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪博客",url:"blog.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"新浪微博",url:"www.weibo.com",providerName:"popDomainProvider",relevancy:0},
{title:"土豆网",url:"www.tudou.com",providerName:"popDomainProvider",relevancy:0},
{title:"酷6网",url:"www.ku6.com",providerName:"popDomainProvider",relevancy:0},
{title:"太平洋电脑网",url:"www.pconline.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"东方财富网 ",url:"www.eastmoney.com",providerName:"popDomainProvider",relevancy:0},
{title:"易车网 ",url:"www.bitauto.com",providerName:"popDomainProvider",relevancy:0},
{title:"39健康网",url:"www.39.net",providerName:"popDomainProvider",relevancy:0},
{title:"起点中文网",url:"www.qidian.com",providerName:"popDomainProvider",relevancy:0},
{title:"多玩游戏网 ",url:"www.duowan.com",providerName:"popDomainProvider",relevancy:0},
{title:"迅雷看看",url:"www.xunlei.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐视频",url:"tv.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"百度文库",url:"wenku.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"2345网址导航",url:"www.2345.com",providerName:"popDomainProvider",relevancy:0},
{title:"乐视网",url:"www.letv.com",providerName:"popDomainProvider",relevancy:0},
{title:"Mtime时光网",url:"www.mtime.com",providerName:"popDomainProvider",relevancy:0},
{title:"好大夫在线",url:"www.haodf.com",providerName:"popDomainProvider",relevancy:0},
{title:"维基百科 ",url:"zh.wikipedia.org",providerName:"popDomainProvider",relevancy:0},
{title:"中国移动通信集团公司",url:"www.10086.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国天气网",url:"www.weather.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"豆瓣电影",url:"movie.douban.com",providerName:"popDomainProvider",relevancy:0},
{title:"56网",url:"www.56.com",providerName:"popDomainProvider",relevancy:0},
{title:"4399小游戏",url:"www.4399.com",providerName:"popDomainProvider",relevancy:0},
{title:"爱问",url:"iask.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"爱奇艺",url:"www.iqiyi.com",providerName:"popDomainProvider",relevancy:0},
{title:"中关村下载 ",url:"xiazai.zol.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"风行网",url:"www.funshion.com",providerName:"popDomainProvider",relevancy:0},
{title:"学信网 ",url:"www.chsi.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"太平洋下载 ",url:"dl.pconline.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"驾校一点通",url:"www.jxedt.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜搜百科 ",url:"baike.soso.com",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰网",url:"www.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"人人网",url:"www.renren.com",providerName:"popDomainProvider",relevancy:0},
{title:"央视网",url:"www.cntv.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国网",url:"www.china.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"新浪新闻",url:"news.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"前程无忧  ",url:"www.51job.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪竞技风暴",url:"sports.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"智联招聘 ",url:"www.zhaopin.com",providerName:"popDomainProvider",relevancy:0},
{title:"Hao123",url:"www.hao123.com",providerName:"popDomainProvider",relevancy:0},
{title:"A67手机电影网",url:"www.a67.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国教育在线",url:"www.eol.cn",providerName:"popDomainProvider",relevancy:0},
{title:"复旦大学",url:"www.fudan.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"谷歌中国",url:"www.google.cn",providerName:"popDomainProvider",relevancy:0},
{title:"浙江大学",url:"www.zju.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"南京大学",url:"www.nju.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"搜房网 ",url:"www.soufun.com",providerName:"popDomainProvider",relevancy:0},
{title:"阿里巴巴",url:"china.alibaba.com",providerName:"popDomainProvider",relevancy:0},
{title:"天涯社区",url:"www.tianya.cn",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯微博",url:"t.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"新华网",url:"www.xinhuanet.com",providerName:"popDomainProvider",relevancy:0},
{title:"百度词典",url:"dict.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"赶集网",url:"www.ganji.com",providerName:"popDomainProvider",relevancy:0},
{title:"360安全中心",url:"www.360.cn",providerName:"popDomainProvider",relevancy:0},
{title:"汽车之家",url:"www.autohome.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"和讯网 ",url:"www.hexun.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狗",url:"www.sogou.com",providerName:"popDomainProvider",relevancy:0},
{title:"中华网",url:"www.china.com",providerName:"popDomainProvider",relevancy:0},
{title:"天极网",url:"www.yesky.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易新闻",url:"news.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"猫扑网",url:"www.mop.com",providerName:"popDomainProvider",relevancy:0},
{title:"爱卡汽车  ",url:"www.xcar.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"电脑之家",url:"www.pchome.net",providerName:"popDomainProvider",relevancy:0},
{title:"当当网",url:"www.dangdang.com",providerName:"popDomainProvider",relevancy:0},
{title:"拍拍网",url:"www.paipai.com",providerName:"popDomainProvider",relevancy:0},
{title:"站长之家",url:"www.chinaz.com",providerName:"popDomainProvider",relevancy:0},
{title:"IP地址查询 ",url:"www.ip138.com",providerName:"popDomainProvider",relevancy:0},
{title:"QQ空间",url:"qzone.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"太平洋汽车网 ",url:"www.pcauto.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"携程旅行网",url:"www.ctrip.com",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰资讯",url:"news.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪财经 ",url:"finance.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯新闻",url:"news.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"去哪儿",url:"www.qunar.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐新闻",url:"news.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"CSDN  ",url:"www.csdn.net",providerName:"popDomainProvider",relevancy:0},
{title:"新浪视频",url:"video.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"慧聪网",url:"www.hc360.com",providerName:"popDomainProvider",relevancy:0},
{title:"17173",url:"www.17173.com",providerName:"popDomainProvider",relevancy:0},
{title:"有道",url:"www.youdao.com",providerName:"popDomainProvider",relevancy:0},
{title:"西安交通大学",url:"www.xjtu.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"21CN",url:"www.21cn.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易博客",url:"blog.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"寻医问药 ",url:"www.xywy.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国新闻网 ",url:"www.chinanews.com",providerName:"popDomainProvider",relevancy:0},
{title:"太平洋游戏网",url:"www.pcgames.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"环球网",url:"www.huanqiu.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国经济网",url:"www.ce.cn",providerName:"popDomainProvider",relevancy:0},
{title:"电玩巴士",url:"www.tgbus.com",providerName:"popDomainProvider",relevancy:0},
{title:"谷歌中国",url:"www.google.com.hk",providerName:"popDomainProvider",relevancy:0},
{title:"爱词霸 ",url:"www.iciba.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐体育 ",url:"sports.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"52PK游戏网",url:"www.52pk.com",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯娱乐 ",url:"ent.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"摇篮网",url:"www.yaolan.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪娱乐",url:"ent.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"178游戏网",url:"www.178.com",providerName:"popDomainProvider",relevancy:0},
{title:"天猫",url:"www.tmall.com",providerName:"popDomainProvider",relevancy:0},
{title:"一听音乐网",url:"www.1ting.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易体育",url:"sports.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"PPTV  ",url:"www.pptv.com",providerName:"popDomainProvider",relevancy:0},
{title:"宝宝树 ",url:"www.babytree.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国建设银行官网",url:"www.ccb.com",providerName:"popDomainProvider",relevancy:0},
{title:"手机中国",url:"www.cnmo.com",providerName:"popDomainProvider",relevancy:0},
{title:"小说阅读网",url:"www.readnovel.com",providerName:"popDomainProvider",relevancy:0},
{title:"音悦台 ",url:"www.yinyuetai.com",providerName:"popDomainProvider",relevancy:0},
{title:"游久网",url:"www.uuu9.com",providerName:"popDomainProvider",relevancy:0},
{title:"太平洋亲子网 ",url:"www.pcbaby.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"爱帮",url:"www.aibang.com",providerName:"popDomainProvider",relevancy:0},
{title:"华军软件园 ",url:"www.onlinedown.net",providerName:"popDomainProvider",relevancy:0},
{title:"支付宝",url:"www.alipay.com",providerName:"popDomainProvider",relevancy:0},
{title:"国际在线",url:"gb.cri.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国知网",url:"www.cnki.net",providerName:"popDomainProvider",relevancy:0},
{title:"17k小说网",url:"www.17k.com",providerName:"popDomainProvider",relevancy:0},
{title:"新民网 ",url:"www.xinmin.cn",providerName:"popDomainProvider",relevancy:0},
{title:"潇湘书院",url:"www.xxsy.net",providerName:"popDomainProvider",relevancy:0},
{title:"晋江文学城",url:"www.jjwxc.net",providerName:"popDomainProvider",relevancy:0},
{title:"8684公交网",url:"www.8684.cn",providerName:"popDomainProvider",relevancy:0},
{title:"网易娱乐",url:"ent.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"招商银行官网",url:"www.cmbchina.com",providerName:"popDomainProvider",relevancy:0},
{title:"电影网",url:"www.m1905.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国工商银行官网",url:"www.icbc.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"红袖添香",url:"www.hongxiu.com",providerName:"popDomainProvider",relevancy:0},
{title:"5173.com ",url:"www.5173.com",providerName:"popDomainProvider",relevancy:0},
{title:"考试吧",url:"www.exam8.com",providerName:"popDomainProvider",relevancy:0},
{title:"百姓网",url:"www.baixing.com",providerName:"popDomainProvider",relevancy:0},
{title:"太平洋女性网",url:"www.pclady.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中公教育",url:"www.offcn.com",providerName:"popDomainProvider",relevancy:0},
{title:"海词",url:"www.dict.cn",providerName:"popDomainProvider",relevancy:0},
{title:"开心网",url:"www.kaixin001.com",providerName:"popDomainProvider",relevancy:0},
{title:"泡泡网",url:"www.pcpop.com",providerName:"popDomainProvider",relevancy:0},
{title:"金融界",url:"www.jrj.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"7k7k小游戏大全",url:"www.7k7k.com",providerName:"popDomainProvider",relevancy:0},
{title:"焦点房地产网",url:"www.focus.cn",providerName:"popDomainProvider",relevancy:0},
{title:"网上车市 ",url:"www.cheshi.com",providerName:"popDomainProvider",relevancy:0},
{title:"京东商城",url:"www.360buy.com",providerName:"popDomainProvider",relevancy:0},
{title:"19楼",url:"www.19lou.com",providerName:"popDomainProvider",relevancy:0},
{title:"PPS网络电视官方网站",url:"www.pps.tv",providerName:"popDomainProvider",relevancy:0},
{title:"铁道部官网",url:"www.12306.cn",providerName:"popDomainProvider",relevancy:0},
{title:"欣欣旅游网",url:"www.cncn.com",providerName:"popDomainProvider",relevancy:0},
{title:"世纪佳缘",url:"www.jiayuan.com",providerName:"popDomainProvider",relevancy:0},
{title:"西祠胡同",url:"www.xici.net",providerName:"popDomainProvider",relevancy:0},
{title:"商都网",url:"www.shangdu.com",providerName:"popDomainProvider",relevancy:0},
{title:"TOM ",url:"www.tom.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国电信网上营业厅",url:"www.189.cn",providerName:"popDomainProvider",relevancy:0},
{title:"瑞丽女性网",url:"www.rayli.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"汽车点评网",url:"www.xgo.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"有问必答网",url:"www.120ask.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国雅虎",url:"cn.yahoo.com",providerName:"popDomainProvider",relevancy:0},
{title:"一淘网",url:"www.etao.com",providerName:"popDomainProvider",relevancy:0},
{title:"1号店",url:"www.yihaodian.com",providerName:"popDomainProvider",relevancy:0},
{title:"163网易免费邮",url:"mail.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪科技",url:"tech.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"YOKA时尚网",url:"www.yoka.com",providerName:"popDomainProvider",relevancy:0},
{title:"铁血网  ",url:"www.tiexue.net",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯视频",url:"v.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"光明网",url:"www.gmw.cn",providerName:"popDomainProvider",relevancy:0},
{title:"IT168  ",url:"www.it168.com",providerName:"popDomainProvider",relevancy:0},
{title:"美团",url:"www.meituan.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易财经",url:"money.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"站长网",url:"www.admin5.com",providerName:"popDomainProvider",relevancy:0},
{title:"东方网",url:"www.eastday.com",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰财经",url:"finance.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"小百科 ",url:"www.baike.com",providerName:"popDomainProvider",relevancy:0},
{title:"青岛新闻网",url:"www.qingdaonews.com",providerName:"popDomainProvider",relevancy:0},
{title:"大众点评网",url:"www.dianping.com",providerName:"popDomainProvider",relevancy:0},
{title:"51.com",url:"www.51.com",providerName:"popDomainProvider",relevancy:0},
{title:"荆楚网 ",url:"www.cnhubei.com",providerName:"popDomainProvider",relevancy:0},
{title:"126网易免费邮",url:"www.126.com",providerName:"popDomainProvider",relevancy:0},
{title:"艺龙旅行网 ",url:"www.elong.com",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯体育",url:"sports.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易科技",url:"tech.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"美食天下 ",url:"www.meishichina.com",providerName:"popDomainProvider",relevancy:0},
{title:"一起游",url:"www.17u.com",providerName:"popDomainProvider",relevancy:0},
{title:"美丽说",url:"www.meilishuo.com",providerName:"popDomainProvider",relevancy:0},
{title:"酷我音乐",url:"www.kuwo.cn",providerName:"popDomainProvider",relevancy:0},
{title:"搜搜问问",url:"wenwen.soso.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国广播网",url:"www.cnr.cn",providerName:"popDomainProvider",relevancy:0},
{title:"豆丁文库",url:"www.docin.com",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰视频",url:"v.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"驴妈妈旅游网  ",url:"www.lvmama.com",providerName:"popDomainProvider",relevancy:0},
{title:"51CTO ",url:"www.51cto.com",providerName:"popDomainProvider",relevancy:0},
{title:"威锋网 ",url:"www.weiphone.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪读书",url:"book.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"途牛旅游网",url:"www.tuniu.com",providerName:"popDomainProvider",relevancy:0},
{title:"安卓网",url:"www.hiapk.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐财经",url:"business.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"华商网",url:"www.hsw.cn",providerName:"popDomainProvider",relevancy:0},
{title:"新浪教育 ",url:"edu.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"大众网",url:"www.dzwww.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易女人",url:"lady.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"爱拍原创",url:"www.aipai.com",providerName:"popDomainProvider",relevancy:0},
{title:"沪江英语",url:"www.hjenglish.com",providerName:"popDomainProvider",relevancy:0},
{title:"天空下载 ",url:"www.skycn.com",providerName:"popDomainProvider",relevancy:0},
{title:"昵图网 ",url:"www.nipic.com",providerName:"popDomainProvider",relevancy:0},
{title:"驱动之家",url:"www.mydrivers.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易微博",url:"t.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰汽车",url:"auto.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪女性",url:"eladies.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"新浪游戏",url:"games.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"机锋网",url:"www.gfan.com",providerName:"popDomainProvider",relevancy:0},
{title:"南海网",url:"www.hinews.cn",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰娱乐",url:"ent.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯读书",url:"book.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐娱乐",url:"yule.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"工业和信息化部备案系统网站",url:"www.miibeian.gov.cn",providerName:"popDomainProvider",relevancy:0},
{title:"PCHome下载 ",url:"download.pchome.net",providerName:"popDomainProvider",relevancy:0},
{title:"游侠网   ",url:"www.ali213.net",providerName:"popDomainProvider",relevancy:0},
{title:"应届生求职网",url:"www.yingjiesheng.com",providerName:"popDomainProvider",relevancy:0},
{title:"齐鲁网",url:"www.iqilu.com",providerName:"popDomainProvider",relevancy:0},
{title:"新东方",url:"www.xdf.cn",providerName:"popDomainProvider",relevancy:0},
{title:"酷讯旅游网",url:"www.kuxun.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国原创音乐基地",url:"www.5sing.com",providerName:"popDomainProvider",relevancy:0},
{title:"电视猫",url:"www.tvmao.com",providerName:"popDomainProvider",relevancy:0},
{title:"766游戏网",url:"www.766.com",providerName:"popDomainProvider",relevancy:0},
{title:"金鹰网",url:"www.hunantv.com",providerName:"popDomainProvider",relevancy:0},
{title:"证券之星",url:"www.stockstar.com",providerName:"popDomainProvider",relevancy:0},
{title:"铁血论坛",url:"bbs.tiexue.net",providerName:"popDomainProvider",relevancy:0},
{title:"游民星空",url:"www.gamersky.com",providerName:"popDomainProvider",relevancy:0},
{title:"硅谷动力",url:"www.enet.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"DISCUZ! 官方站  ",url:"www.discuz.net",providerName:"popDomainProvider",relevancy:0},
{title:"谷歌翻译",url:"translate.google.cn",providerName:"popDomainProvider",relevancy:0},
{title:"凡客诚品",url:"www.vancl.com",providerName:"popDomainProvider",relevancy:0},
{title:"虎扑体育 ",url:"www.hupu.com",providerName:"popDomainProvider",relevancy:0},
{title:"酷狗音乐",url:"www.kugou.com",providerName:"popDomainProvider",relevancy:0},
{title:"中彩网 ",url:"www.zhcw.com",providerName:"popDomainProvider",relevancy:0},
{title:"博宝艺术网",url:"www.artxun.com",providerName:"popDomainProvider",relevancy:0},
{title:"安居客 ",url:"www.anjuke.com",providerName:"popDomainProvider",relevancy:0},
{title:"CNTV新闻台",url:"news.cntv.cn",providerName:"popDomainProvider",relevancy:0},
{title:"大街网 ",url:"www.dajie.com",providerName:"popDomainProvider",relevancy:0},
{title:"纵横中文网",url:"www.zongheng.com",providerName:"popDomainProvider",relevancy:0},
{title:"海报网 ",url:"www.haibao.cn",providerName:"popDomainProvider",relevancy:0},
{title:"九酷音乐网",url:"www.9ku.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐汽车",url:"auto.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"07073游戏网",url:"www.07073.com",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯财经",url:"finance.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"沪江网",url:"www.hujiang.com",providerName:"popDomainProvider",relevancy:0},
{title:"当乐网",url:"www.d.cn",providerName:"popDomainProvider",relevancy:0},
{title:"丁香园",url:"www.dxy.cn",providerName:"popDomainProvider",relevancy:0},
{title:"考试大",url:"www.233.com",providerName:"popDomainProvider",relevancy:0},
{title:"无忧考网",url:"www.51test.net",providerName:"popDomainProvider",relevancy:0},
{title:"华讯财经",url:"www.591hx.com",providerName:"popDomainProvider",relevancy:0},
{title:"百度MP3",url:"mp3.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"360doc个人图书馆",url:"www.360doc.com",providerName:"popDomainProvider",relevancy:0},
{title:"NBA中国官方网站 ",url:"china.nba.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪汽车",url:"auto.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"91游戏娱乐门户",url:"www.91.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪星座",url:"astro.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"2345软件大全",url:"www.duote.com",providerName:"popDomainProvider",relevancy:0},
{title:"谷歌台湾",url:"www.google.com.tw",providerName:"popDomainProvider",relevancy:0},
{title:"非凡软件站",url:"www.crsky.com",providerName:"popDomainProvider",relevancy:0},
{title:"我爱购物网",url:"www.55bbs.com",providerName:"popDomainProvider",relevancy:0},
{title:"大旗网",url:"www.daqi.com",providerName:"popDomainProvider",relevancy:0},
{title:"爱美网",url:"www.lady8844.com",providerName:"popDomainProvider",relevancy:0},
{title:"团800",url:"www.tuan800.com",providerName:"popDomainProvider",relevancy:0},
{title:"网易汽车",url:"auto.163.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐女人",url:"women.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"北青网",url:"www.ynet.com",providerName:"popDomainProvider",relevancy:0},
{title:"365地产家居",url:"www.house365.com",providerName:"popDomainProvider",relevancy:0},
{title:"POCO.CN",url:"www.poco.cn",providerName:"popDomainProvider",relevancy:0},
{title:"VeryCD  ",url:"www.verycd.com",providerName:"popDomainProvider",relevancy:0},
{title:"拉手网",url:"www.lashou.com",providerName:"popDomainProvider",relevancy:0},
{title:"39健康问答",url:"ask.39.net",providerName:"popDomainProvider",relevancy:0},
{title:"豆果网",url:"www.douguo.com",providerName:"popDomainProvider",relevancy:0},
{title:"图吧 ",url:"www.mapbar.com",providerName:"popDomainProvider",relevancy:0},
{title:"快递100 ",url:"www.kuaidi100.com",providerName:"popDomainProvider",relevancy:0},
{title:"蜂鸟网",url:"www.fengniao.com",providerName:"popDomainProvider",relevancy:0},
{title:"OnlyLady女人志",url:"www.onlylady.com",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯女性",url:"lady.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国平安保险",url:"www.pingan.com",providerName:"popDomainProvider",relevancy:0},
{title:"下载吧",url:"www.xiazaiba.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国农业银行官网",url:"www.abchina.com",providerName:"popDomainProvider",relevancy:0},
{title:"苏宁易购",url:"www.suning.com",providerName:"popDomainProvider",relevancy:0},
{title:"点点网",url:"www.diandian.com",providerName:"popDomainProvider",relevancy:0},
{title:"亚马逊中国",url:"www.amazon.cn",providerName:"popDomainProvider",relevancy:0},
{title:"百度新闻搜索",url:"news.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"QQ邮箱",url:"mail.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"四川在线",url:"www.scol.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐微博",url:"t.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"蘑菇街",url:"www.mogujie.com",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯汽车 ",url:"auto.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"360安全网址导航",url:"hao.360.cn",providerName:"popDomainProvider",relevancy:0},
{title:"手机之家",url:"www.imobile.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"到到网",url:"www.daodao.com",providerName:"popDomainProvider",relevancy:0},
{title:"淘米网",url:"www.61.com",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯科技",url:"tech.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"清华大学",url:"www.tsinghua.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"Wed114结婚网",url:"www.wed114.cn",providerName:"popDomainProvider",relevancy:0},
{title:"丫丫网",url:"www.iyaya.com",providerName:"popDomainProvider",relevancy:0},
{title:"聚美优品",url:"www.jumei.com",providerName:"popDomainProvider",relevancy:0},
{title:"户外资料网 ",url:"www.8264.com",providerName:"popDomainProvider",relevancy:0},
{title:"比特网",url:"www.chinabyte.com",providerName:"popDomainProvider",relevancy:0},
{title:"易购网",url:"www.egou.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狗音乐",url:"mp3.sogou.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国汽车消费网",url:"www.315che.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国银行官网",url:"www.boc.cn",providerName:"popDomainProvider",relevancy:0},
{title:"金投网",url:"www.cngold.org",providerName:"popDomainProvider",relevancy:0},
{title:"搜库",url:"www.soku.com",providerName:"popDomainProvider",relevancy:0},
{title:"育儿网",url:"www.ci123.com",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰论坛",url:"bbs.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"e度教育网",url:"www.eduu.com",providerName:"popDomainProvider",relevancy:0},
{title:"中华会计网校",url:"www.chinaacc.com",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰博报",url:"blog.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"爱漫画",url:"www.imanhua.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐IT",url:"it.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"激动网 ",url:"www.joy.cn",providerName:"popDomainProvider",relevancy:0},
{title:"搜狗地图",url:"map.sogou.com",providerName:"popDomainProvider",relevancy:0},
{title:"中信金融网",url:"www.ecitic.com",providerName:"popDomainProvider",relevancy:0},
{title:"淘车网",url:"www.taoche.com",providerName:"popDomainProvider",relevancy:0},
{title:"中华网军事 ",url:"military.china.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪军事",url:"mil.news.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国联通网上营业厅",url:"www.10010.com",providerName:"popDomainProvider",relevancy:0},
{title:"太平洋家居网 ",url:"www.pchouse.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中华网社区",url:"club.china.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国农业银行网站",url:"www.95599.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中山大学",url:"www.sysu.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"Dospy智能手机网",url:"www.dospy.com",providerName:"popDomainProvider",relevancy:0},
{title:"联想中国",url:"www.lenovo.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"龙虎网",url:"www.longhoo.net",providerName:"popDomainProvider",relevancy:0},
{title:"交通银行官网",url:"www.bankcomm.com",providerName:"popDomainProvider",relevancy:0},
{title:"博客园",url:"www.cnblogs.com",providerName:"popDomainProvider",relevancy:0},
{title:"西陆网 ",url:"www.xilu.com",providerName:"popDomainProvider",relevancy:0},
{title:"三联素材 ",url:"www.3lian.com",providerName:"popDomainProvider",relevancy:0},
{title:"豆瓣读书",url:"book.douban.com",providerName:"popDomainProvider",relevancy:0},
{title:"小米网",url:"www.xiaomi.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国战略网 ",url:"www.chinaiiss.com",providerName:"popDomainProvider",relevancy:0},
{title:"大公网",url:"www.takungpao.com",providerName:"popDomainProvider",relevancy:0},
{title:"上海热线",url:"www.online.sh.cn",providerName:"popDomainProvider",relevancy:0},
{title:"奥一网",url:"www.oeeee.com",providerName:"popDomainProvider",relevancy:0},
{title:"同花顺金融服务网",url:"www.10jqka.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"蚂蜂窝 ",url:"www.mafengwo.cn",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰网时尚",url:"fashion.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"雅昌艺术网",url:"www.artron.net",providerName:"popDomainProvider",relevancy:0},
{title:"华律网",url:"www.66law.cn",providerName:"popDomainProvider",relevancy:0},
{title:"美乐乐家具网",url:"www.meilele.com",providerName:"popDomainProvider",relevancy:0},
{title:"大麦网",url:"www.damai.cn",providerName:"popDomainProvider",relevancy:0},
{title:"国美电器网上商城",url:"www.gome.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"天涯问答",url:"wenda.tianya.cn",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯教育",url:"edu.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐博客",url:"blog.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"塞班智能手机论坛",url:"bbs.dospy.com",providerName:"popDomainProvider",relevancy:0},
{title:"聚划算",url:"ju.taobao.com",providerName:"popDomainProvider",relevancy:0},
{title:"站长工具  ",url:"tool.chinaz.com",providerName:"popDomainProvider",relevancy:0},
{title:"查字典",url:"www.chazidian.com",providerName:"popDomainProvider",relevancy:0},
{title:"本地宝",url:"www.bendibao.com",providerName:"popDomainProvider",relevancy:0},
{title:"火车网 ",url:"www.huoche.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国人才热线 ",url:"www.cjol.com",providerName:"popDomainProvider",relevancy:0},
{title:"应届毕业生求职网 ",url:"www.yjbys.com",providerName:"popDomainProvider",relevancy:0},
{title:"道客巴巴",url:"www.doc88.com",providerName:"popDomainProvider",relevancy:0},
{title:"城市吧",url:"www.city8.com",providerName:"popDomainProvider",relevancy:0},
{title:"淘房网",url:"www.taofang.com",providerName:"popDomainProvider",relevancy:0},
{title:"叶子猪游戏网",url:"www.yzz.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国工商行政总局",url:"www.saic.gov.cn",providerName:"popDomainProvider",relevancy:0},
{title:"解放牛网",url:"www.jfdaily.com",providerName:"popDomainProvider",relevancy:0},
{title:"汽车之家论坛",url:"club.autohome.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"爱丽时尚",url:"www.aili.com",providerName:"popDomainProvider",relevancy:0},
{title:"人民网健康频道",url:"health.people.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"法律快车",url:"www.lawtime.cn",providerName:"popDomainProvider",relevancy:0},
{title:"ZOL手机",url:"mobile.zol.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"机锋论坛  ",url:"bbs.gfan.com",providerName:"popDomainProvider",relevancy:0},
{title:"库巴购物网",url:"www.coo8.com",providerName:"popDomainProvider",relevancy:0},
{title:"银率网",url:"www.bankrate.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"百度团购导航",url:"tuan.baidu.com",providerName:"popDomainProvider",relevancy:0},
{title:"河北新闻网",url:"www.hebnews.cn",providerName:"popDomainProvider",relevancy:0},
{title:"21世纪网",url:"www.21cbh.com",providerName:"popDomainProvider",relevancy:0},
{title:"木蚂蚁 ",url:"www.mumayi.com",providerName:"popDomainProvider",relevancy:0},
{title:"华声在线",url:"www.voc.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中华英才网",url:"www.chinahr.com",providerName:"popDomainProvider",relevancy:0},
{title:"今题网",url:"jinti.com",providerName:"popDomainProvider",relevancy:0},
{title:"易讯",url:"www.51buy.com",providerName:"popDomainProvider",relevancy:0},
{title:"ELLE",url:"www.ellechina.com",providerName:"popDomainProvider",relevancy:0},
{title:"人民网财经",url:"finance.people.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"易登网",url:"www.edeng.cn",providerName:"popDomainProvider",relevancy:0},
{title:"东北网",url:"www.dbw.cn",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯星座 ",url:"astro.lady.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"上海交通大学",url:"www.sjtu.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"6间房 ",url:"www.6.cn",providerName:"popDomainProvider",relevancy:0},
{title:"凯迪网络",url:"www.kdnet.net",providerName:"popDomainProvider",relevancy:0},
{title:"谷歌地图",url:"ditu.google.cn",providerName:"popDomainProvider",relevancy:0},
{title:"玩家网 ",url:"www.cngba.com",providerName:"popDomainProvider",relevancy:0},
{title:"找法网",url:"china.findlaw.cn",providerName:"popDomainProvider",relevancy:0},
{title:"苹果园 ",url:"www.app111.com",providerName:"popDomainProvider",relevancy:0},
{title:"MBA智库",url:"www.mbalib.com",providerName:"popDomainProvider",relevancy:0},
{title:"ChinaRen校友录",url:"www.chinaren.com",providerName:"popDomainProvider",relevancy:0},
{title:"悠哉旅游网 ",url:"www.uzai.com",providerName:"popDomainProvider",relevancy:0},
{title:"逐浪网 ",url:"www.zhulang.com",providerName:"popDomainProvider",relevancy:0},
{title:"中金在线 ",url:"www.cnfol.com",providerName:"popDomainProvider",relevancy:0},
{title:"3DMGAME ",url:"www.3dmgame.com",providerName:"popDomainProvider",relevancy:0},
{title:"必途网",url:"www.b2b.cn",providerName:"popDomainProvider",relevancy:0},
{title:"直播吧",url:"www.zhibo8.cc",providerName:"popDomainProvider",relevancy:0},
{title:"华中科技大学",url:"www.hust.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"看看新闻网",url:"www.kankanews.com",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐教育",url:"learning.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"考研网",url:"www.kaoyan.com",providerName:"popDomainProvider",relevancy:0},
{title:"锐派游戏 ",url:"www.replays.net",providerName:"popDomainProvider",relevancy:0},
{title:"食品商务网",url:"www.21food.cn",providerName:"popDomainProvider",relevancy:0},
{title:"乐途旅游网",url:"www.lotour.com",providerName:"popDomainProvider",relevancy:0},
{title:"列表网 ",url:"www.liebiao.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪家居 ",url:"jiaju.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"凤凰网科技",url:"tech.ifeng.com",providerName:"popDomainProvider",relevancy:0},
{title:"威锋网论坛",url:"bbs.weiphone.com",providerName:"popDomainProvider",relevancy:0},
{title:"环球网军事",url:"mil.huanqiu.com",providerName:"popDomainProvider",relevancy:0},
{title:"3533手机世界",url:"www.3533.com",providerName:"popDomainProvider",relevancy:0},
{title:"虾米音乐网",url:"www.xiami.com",providerName:"popDomainProvider",relevancy:0},
{title:"又拍网",url:"www.yupoo.com",providerName:"popDomainProvider",relevancy:0},
{title:"起点女生网",url:"www.qdmm.com",providerName:"popDomainProvider",relevancy:0},
{title:"yy语音",url:"www.yy.com",providerName:"popDomainProvider",relevancy:0},
{title:"香港文汇网",url:"www.wenweipo.com",providerName:"popDomainProvider",relevancy:0},
{title:"四川新闻网 ",url:"www.newssc.org",providerName:"popDomainProvider",relevancy:0},
{title:"战网",url:"www.battlenet.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"言情小说吧",url:"www.xs8.cn",providerName:"popDomainProvider",relevancy:0},
{title:"114啦",url:"www.114la.com",providerName:"popDomainProvider",relevancy:0},
{title:"体坛网",url:"www.titan24.com",providerName:"popDomainProvider",relevancy:0},
{title:"勤加缘网",url:"www.qjy168.com",providerName:"popDomainProvider",relevancy:0},
{title:"游迅网",url:"www.yxdown.com",providerName:"popDomainProvider",relevancy:0},
{title:"3366小游戏",url:"www.3366.com",providerName:"popDomainProvider",relevancy:0},
{title:"完美世界",url:"www.wanmei.com",providerName:"popDomainProvider",relevancy:0},
{title:"有妖气",url:"www.u17.com",providerName:"popDomainProvider",relevancy:0},
{title:"糯米网",url:"www.nuomi.com",providerName:"popDomainProvider",relevancy:0},
{title:"飞华健康网",url:"www.fh21.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"和家网",url:"www.51hejia.com",providerName:"popDomainProvider",relevancy:0},
{title:"放心医苑",url:"www.fx120.net",providerName:"popDomainProvider",relevancy:0},
{title:"心食谱",url:"www.xinshipu.com",providerName:"popDomainProvider",relevancy:0},
{title:"土巴兔",url:"www.to8to.com",providerName:"popDomainProvider",relevancy:0},
{title:"金山逍遥",url:"www.xoyo.com",providerName:"popDomainProvider",relevancy:0},
{title:"3158招商加盟网",url:"www.3158.cn",providerName:"popDomainProvider",relevancy:0},
{title:"家庭医生在线",url:"www.familydoctor.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"九正建材网",url:"www.jc001.cn",providerName:"popDomainProvider",relevancy:0},
{title:"查查吧",url:"www.chachaba.com",providerName:"popDomainProvider",relevancy:0},
{title:"城市中国",url:"www.ccoo.cn",providerName:"popDomainProvider",relevancy:0},
{title:"2144小游戏",url:"www.2144.cn",providerName:"popDomainProvider",relevancy:0},
{title:"万维家电网",url:"www.ea3w.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国网财经",url:"finance.china.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"学科网",url:"www.zxxk.com",providerName:"popDomainProvider",relevancy:0},
{title:"浙江在线",url:"www.zjol.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"果壳网",url:"www.guokr.com",providerName:"popDomainProvider",relevancy:0},
{title:"人民网教育频道",url:"edu.people.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐社区",url:"club.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"数字英才网",url:"www.01hr.com",providerName:"popDomainProvider",relevancy:0},
{title:"火车网",url:"www.huoche.net",providerName:"popDomainProvider",relevancy:0},
{title:"站酷",url:"www.zcool.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"腾讯数码",url:"digi.tech.qq.com",providerName:"popDomainProvider",relevancy:0},
{title:"新浪乐居",url:"house.sina.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"美食杰",url:"www.meishij.net",providerName:"popDomainProvider",relevancy:0},
{title:"我爱卡",url:"www.51credit.com",providerName:"popDomainProvider",relevancy:0},
{title:"武汉大学",url:"www.whu.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中华人民共和国海关总署",url:"www.customs.gov.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国邮政储蓄银行",url:"www.psbc.com",providerName:"popDomainProvider",relevancy:0},
{title:"PC6下载站",url:"www.pc6.com",providerName:"popDomainProvider",relevancy:0},
{title:"合肥热线",url:"www.hefei.cc",providerName:"popDomainProvider",relevancy:0},
{title:"VOGUE时尚网",url:"www.vogue.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"人民网娱乐频道",url:"ent.people.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"猪八戒",url:"www.zhubajie.com",providerName:"popDomainProvider",relevancy:0},
{title:"梦芭莎",url:"www.moonbasa.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国邮政速递物流",url:"www.ems.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"百合网",url:"www.baihe.com",providerName:"popDomainProvider",relevancy:0},
{title:"科学网",url:"www.sciencenet.cn",providerName:"popDomainProvider",relevancy:0},
{title:"天涯博客",url:"blog.tianya.cn",providerName:"popDomainProvider",relevancy:0},
{title:"搜狐母婴频道 ",url:"baobao.sohu.com",providerName:"popDomainProvider",relevancy:0},
{title:"二手车之家",url:"www.che168.com",providerName:"popDomainProvider",relevancy:0},
{title:"东方热线",url:"www.cnool.net",providerName:"popDomainProvider",relevancy:0},
{title:"华东师范大学",url:"www.ecnu.edu.cn",providerName:"popDomainProvider",relevancy:0},
{title:"全景网 ",url:"www.p5w.net",providerName:"popDomainProvider",relevancy:0},
{title:"中顾法律网",url:"www.9ask.cn",providerName:"popDomainProvider",relevancy:0},
{title:"CSDN博客",url:"blog.csdn.net",providerName:"popDomainProvider",relevancy:0},
{title:"落伍者论坛",url:"www.im286.com",providerName:"popDomainProvider",relevancy:0},
{title:"苹果官网",url:"www.apple.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"99健康网 ",url:"www.99.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"北方网",url:"www.enorth.com.cn",providerName:"popDomainProvider",relevancy:0},
{title:"朋友网",url:"www.pengyou.com",providerName:"popDomainProvider",relevancy:0},
{title:"51汽车",url:"www.51auto.com",providerName:"popDomainProvider",relevancy:0},
{title:"中国商务部网站",url:"www.mofcom.gov.cn",providerName:"popDomainProvider",relevancy:0},
{title:"中国科学院",url:"www.cas.cn",providerName:"popDomainProvider",relevancy:0},
{title:"汽车中国 ",url:"www.carschina.com",providerName:"popDomainProvider",relevancy:0}];
